---
- hosts: droplets
  sudo: yes
  gather_facts: no

  tasks:
  - name: ensure apt cache is up to date
    apt: update_cache=yes
  - name: ensure packages are installed
    apt: name={{item}}
    with_items:
        - nginx
  - name: ensure default is removed
    command: /bin/rm /etc/nginx/sites-enabled/default
  - name: ensure chat config is uploaded
    copy: src=../static/chat.conf dest=/etc/nginx/sites-enabled/chat.conf owner=root group=root mode=0644
  - name: ensure nginx is started
    service: name=nginx state=started
